### ISSUE TITLE
Kovert isn't respecting defaulted query params

### ISSUE THREAD

**Issue by adambrown** [kohesive/kovert#33]
e.g.

    /**
     *
     *  HTTP GET /path/thing/:thingid/subthing/subsubthings?size=50&forwardMarker=invoice_id
     *
     */
    fun Context.listThingByThingidSubthingSubsubthing(thingid: String, size: Int = 50, forwardMarker: String? = null): Promise<WithScrolling<String, List<Thing>>, Exception> {

makes the rest client always provide size and forwardMarker params even though there are sensible defaults that could be used.

**Comment by apatrida** [comment]
fixed in `0.13.0` to be released in the next few hours.
