### ISSUE TITLE
logout in example web app doesn't log out

### ISSUE THREAD

**Issue by kenkyee** [kohesive/kovert#36]
To reproduce:
- start example kovert app
- go to localhost:8080
- click on login link
- type in franky/123 for creds as prompted
- click on logout link
- click on login link again (it should prompt for a username/password at this point but doesn't)

**Comment by apatrida** [comment]
It doesn't logout because it uses basic auth, and basic auth does not have a logout.  the browser remembers and sends the headers and so logging out a server-side session does nothing.

A more realistic auth handler (JDBC, OAUTH, JWT) would work fine.

**Comment by kenkyee** [comment]
There is a hack, but I agree using JWT or OAuth would be the right way to do it :-)
http://tuhrig.de/basic-auth-log-out-with-javascript/
